baseurl = "https://diegocunha.me/"
# Shown in the side menu
copyright = "&copy; 2016. Some rights reserved."
canonifyurls = true
paginate = 10
theme = "hyde-x"
disqusShortname = "diegocunha-me"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true


[author]
    name = "Diego Rogerio da Cunha"
    homepage = "https://diegocunha.me"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "blog/:year/:month/:day/:title"

[taxonomies]
  tag = "tags"
  topic = "categories"

[params]
  # Shown in the home page
  truncate = true
  defaultDescription = "Sharing the code"
  hideReadingTime = false
  theme = "theme-base-0d"
  googleAnalytics = "UA-111345881-1"
  home = "Home"
  github = "https://github.com/diegorcunha"
  bitbucket = ""
  stackOverflow = ""
  linkedin = "https://www.linkedin.com/in/diegorogeriodacunha/"
  googleplus = ""
  facebook = ""
  twitter = "https://twitter.com/diegoAnalista"
  youtube = ""

  [menu]
    # Shown in the side menu.
    [[menu.main]]
      name = "Home"
      pre = "<i class='fa fa-home fa-fw'></i>"
      weight = 0
      identifier = "home"
      url = "/"
    [[menu.main]]
      name = "Portuguese"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 1
      identifier = "portuguese"
      url = "https://diegocunha.me/tags/portugues"
    [[menu.main]]
      name = "English"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 2
      identifier = "english"
      url = "https://diegocunha.me/tags/english"
    [[menu.main]]
      name = "About"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 3
      identifier = "about"
      url = "/about/"


  #  [[menu.main]]
  #    name = "Contact"
  #    pre = "<i class='fa fa-phone fa-fw'></i>"
  #    weight = 3
  #    url = "/contact/"
